platform :ios, '6.0'

pod 'ECSlidingViewController', '~> 0.9.0'
pod 'MeetupOAuth2Client', :git => 'https://github.com/w5mith/MeetupOAuth2Client.git' 

link_with ['CocoaHeadsBNE', 'CocoaHeadsBNETest']
